import asyncio
import logging
import re

import resend

from config import get_settings

logger = logging.getLogger(__name__)


def _markdown_to_html(md: str) -> str:
    """Convert markdown to simple HTML suitable for email."""
    html = md
    # Headers
    html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
    html = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html, flags=re.MULTILINE)
    # Bold / italic
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)
    # Bullet lists — wrap consecutive li lines in <ul>
    html = re.sub(r"^\* (.+)$", r"<li>\1</li>", html, flags=re.MULTILINE)
    html = re.sub(r"^- (.+)$", r"<li>\1</li>", html, flags=re.MULTILINE)
    html = re.sub(r"(<li>.*?</li>\n?)+", lambda m: f"<ul>{m.group()}</ul>", html, flags=re.DOTALL)
    # Paragraphs: blank-line separated blocks not already in tags
    paragraphs = html.split("\n\n")
    result = []
    for p in paragraphs:
        p = p.strip()
        if not p:
            continue
        if p.startswith("<"):
            result.append(p)
        else:
            result.append(f"<p>{p.replace(chr(10), '<br>')}</p>")
    return "\n".join(result)


async def send_plan_email(to_email: str, plan_content: str, destination: str = "your destination") -> bool:
    """Send a travel plan to the given email via Resend. Returns True on success."""
    settings = get_settings()
    if not settings.resend_api_key:
        logger.error("RESEND_API_KEY not configured — cannot send email")
        return False

    resend.api_key = settings.resend_api_key

    html_body = f"""
    <div style="font-family: Arial, sans-serif; max-width: 640px; margin: 0 auto; color: #1a1a2e;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                  padding: 32px; border-radius: 12px 12px 0 0; text-align: center;">
        <h1 style="color: white; margin: 0; font-size: 24px;">✈️ Your Travel Plan</h1>
        <p style="color: rgba(255,255,255,0.85); margin: 8px 0 0;">
          Trip to {destination}
        </p>
      </div>
      <div style="background: #ffffff; padding: 32px; border-radius: 0 0 12px 12px;
                  border: 1px solid #e8e8f0;">
        {_markdown_to_html(plan_content)}
      </div>
      <p style="text-align: center; color: #888; font-size: 12px; margin-top: 16px;">
        Generated by AI Travel Planner
      </p>
    </div>
    """

    try:
        await asyncio.to_thread(
            lambda: resend.Emails.send({
                "from": "AI Travel Planner <onboarding@resend.dev>",
                "to": to_email,
                "subject": f"Your Travel Plan — {destination}",
                "html": html_body,
            })
        )
        logger.info("Travel plan email sent to %s", to_email)
        return True
    except Exception as exc:
        logger.error("Failed to send email to %s: %s", to_email, exc)
        return False
