name: ai_travel_planner

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_vector
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-schema.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d vectordb"]
      interval: 10s
      timeout: 5s
      retries: 5

  vault:
    image: hashicorp/vault:1.18
    container_name: vault
    restart: always
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN:-myroot}
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: http://localhost:8200
      VAULT_TOKEN: ${VAULT_TOKEN:-myroot}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY:-}
    ports:
      - "8200:8200"
    volumes:
      - ./vault-init.sh:/vault-init.sh
    entrypoint: ["sh", "-c", "vault server -dev & sleep 2 && sh /vault-init.sh && wait"]
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/vectordb
      DOCUMENTS_DIR: /app/documents
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN:-myroot}
      #AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY:-}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT:-}
      AZURE_STRONG_MODEL: ${AZURE_STRONG_MODEL:-Kimi-K2.6-1}
      AZURE_CHEAP_MODEL: ${AZURE_CHEAP_MODEL:-o4-mini}
      AZURE_EMBEDDING_MODEL: ${AZURE_EMBEDDING_MODEL:-text-embedding-3-small-1}
      LANGSMITH_TRACING: ${LANGSMITH_TRACING:-true}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY:-}
      LANGSMITH_ENDPOINT: ${LANGSMITH_ENDPOINT:-https://api.smith.langchain.com}
      LANGSMITH_PROJECT: ${LANGSMITH_PROJECT:-}
    volumes:
      - ./documents:/app/documents:ro
      - ./.env:/.env:ro
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      vault:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
